"""
fetch_github_issues.py — Paginate through GitHub Issues and export them to CSV.

This is a sample web/API script generated by Copilot Script Agent.
It demonstrates: API pagination with rate-limit handling, tqdm progress,
--dry-run support, and secrets loaded from environment variables.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
import time
from pathlib import Path
from typing import Any

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import requests
from tqdm import tqdm

from scripts.common.logger import get_logger

log = get_logger(__name__)

GITHUB_API = "https://api.github.com"
ISSUES_FIELDS = ["number", "title", "state", "created_at", "updated_at", "html_url", "user"]


def _headers(token: str | None) -> dict[str, str]:
    h = {"Accept": "application/vnd.github+json"}
    if token:
        h["Authorization"] = f"token {token}"
    return h


def _log_perf(stage: str, started_at: float, **fields: Any) -> None:
    elapsed_ms = (time.perf_counter() - started_at) * 1000
    metrics = " ".join(f"{k}={v}" for k, v in fields.items())
    log.info("perf.%s elapsed_ms=%.2f %s", stage, elapsed_ms, metrics)


def _request_page(
    session: requests.Session,
    url: str,
    *,
    headers: dict[str, str],
    params: dict[str, Any],
    max_retries: int = 4,
    max_backoff_seconds: int = 30,
) -> requests.Response:
    """Request a single API page with bounded retries/backoff."""
    for attempt in range(max_retries + 1):
        try:
            resp = session.get(url, headers=headers, params=params, timeout=30)
        except requests.RequestException as exc:
            if attempt >= max_retries:
                raise RuntimeError(f"GitHub request failed after {max_retries + 1} attempts.") from exc
            wait = min(max_backoff_seconds, 2**attempt)
            log.warning(
                "Request error on attempt %d/%d: %s; retrying in %ds.",
                attempt + 1,
                max_retries + 1,
                exc,
                wait,
            )
            time.sleep(wait)
            continue

        try:
            remaining = int(resp.headers.get("X-RateLimit-Remaining", "1"))
        except (TypeError, ValueError):
            remaining = 1
        if resp.status_code in (403, 429) and (remaining == 0 or resp.status_code == 429):
            if attempt >= max_retries:
                resp.raise_for_status()
            reset_header = resp.headers.get("X-RateLimit-Reset")
            if reset_header and remaining == 0:
                try:
                    wait = max(1, int(reset_header) - int(time.time()))
                except (TypeError, ValueError):
                    wait = min(max_backoff_seconds, 2**attempt)
            else:
                wait = min(max_backoff_seconds, 2**attempt)
            log.warning(
                "Rate limit encountered on attempt %d/%d; waiting %ds.",
                attempt + 1,
                max_retries + 1,
                wait,
            )
            time.sleep(wait)
            continue

        if 500 <= resp.status_code < 600:
            if attempt >= max_retries:
                resp.raise_for_status()
            wait = min(max_backoff_seconds, 2**attempt)
            log.warning(
                "GitHub server error %d on attempt %d/%d; retrying in %ds.",
                resp.status_code,
                attempt + 1,
                max_retries + 1,
                wait,
            )
            time.sleep(wait)
            continue

        resp.raise_for_status()
        return resp

    raise RuntimeError("Exceeded retry budget while fetching GitHub issues.")


def issue_to_row(issue: dict[str, Any]) -> dict[str, str]:
    return {
        "number": str(issue.get("number", "")),
        "title": issue.get("title", ""),
        "state": issue.get("state", ""),
        "created_at": issue.get("created_at", ""),
        "updated_at": issue.get("updated_at", ""),
        "html_url": issue.get("html_url", ""),
        "user": (issue.get("user") or {}).get("login", ""),
    }


def stream_issues_to_csv(
    owner: str,
    repo: str,
    token: str | None,
    output: Path,
    *,
    state: str = "all",
    per_page: int = 100,
    dry_run: bool = False,
    max_pages: int | None = None,
) -> int:
    """Fetch paginated issues and stream output to CSV (or dry-run counters)."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues"
    headers = _headers(token)
    page = 1
    total_issues = 0
    fetched_pages = 0
    write_started_at = time.perf_counter()

    with requests.Session() as session:
        with tqdm(desc="Fetching issues", unit="page") as bar:
            writer: csv.DictWriter | None = None
            out_fh = None
            if not dry_run:
                output.parent.mkdir(parents=True, exist_ok=True)
                out_fh = output.open("w", encoding="utf-8", newline="")
                writer = csv.DictWriter(out_fh, fieldnames=ISSUES_FIELDS)
                writer.writeheader()
            try:
                while True:
                    if max_pages is not None and fetched_pages >= max_pages:
                        break
                    fetch_started_at = time.perf_counter()
                    resp = _request_page(
                        session,
                        url,
                        headers=headers,
                        params={"state": state, "per_page": per_page, "page": page},
                    )
                    page_items = resp.json()
                    issues = [item for item in page_items if "pull_request" not in item]
                    _log_perf(
                        "fetch_page",
                        fetch_started_at,
                        page=page,
                        items=len(page_items),
                        issues=len(issues),
                    )
                    if not page_items:
                        break

                    for issue in issues:
                        if writer is not None:
                            writer.writerow(issue_to_row(issue))
                        total_issues += 1

                    fetched_pages += 1
                    page += 1
                    bar.update(1)
            finally:
                if out_fh is not None:
                    out_fh.close()

    _log_perf("export_write", write_started_at, pages=fetched_pages, issues=total_issues, dry_run=dry_run)
    return total_issues


def main(args: argparse.Namespace) -> int:
    log.info(
        "fetch_github_issues starting (repo=%s/%s, dry_run=%s)",
        args.owner,
        args.repo,
        args.dry_run,
    )

    output = Path(args.output)
    token = args.token or os.environ.get("GITHUB_TOKEN")
    total = stream_issues_to_csv(
        args.owner,
        args.repo,
        token,
        output,
        state=args.state,
        dry_run=args.dry_run,
        max_pages=args.max_pages,
    )

    if args.dry_run:
        log.info("[dry-run] Would write %d row(s) to '%s'.", total, output)
        return 0

    log.info("Wrote %d issue(s) to '%s'.", total, output)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch GitHub Issues for a repository and export to CSV."
    )
    parser.add_argument("owner", help="Repository owner (user or org).")
    parser.add_argument("repo", help="Repository name.")
    parser.add_argument("--output", default="issues.csv", help="Output CSV path.")
    parser.add_argument("--state", default="all", choices=["open", "closed", "all"])
    parser.add_argument(
        "--token",
        default=None,
        help="GitHub personal access token (or set GITHUB_TOKEN env var).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    parser.add_argument(
        "--max-pages",
        type=int,
        default=None,
        help="Optional cap on fetched API pages.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
