"""
fetch_github_issues.py — Paginate through GitHub Issues and export them to CSV.

This is a sample web/API script generated by Copilot Script Agent.
It demonstrates: API pagination with rate-limit handling, tqdm progress,
--dry-run support, and secrets loaded from environment variables.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
import time
import tracemalloc
from pathlib import Path
from typing import Iterator

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import requests
from requests.adapters import HTTPAdapter
from tqdm import tqdm
from urllib3.util.retry import Retry

from scripts.common.logger import get_logger

log = get_logger(__name__)

if not tracemalloc.is_tracing():
    tracemalloc.start()

GITHUB_API = "https://api.github.com"
ISSUES_FIELDS = ["number", "title", "state", "created_at", "updated_at", "html_url", "user"]


def _memory_kib() -> tuple[float, float]:
    current, peak = tracemalloc.get_traced_memory()
    return current / 1024.0, peak / 1024.0


def _headers(token: str | None) -> dict[str, str]:
    h = {"Accept": "application/vnd.github+json"}
    if token:
        h["Authorization"] = "Bearer " + token
    return h


def _build_session() -> requests.Session:
    retry = Retry(
        total=5,
        backoff_factor=1.0,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=("GET",),
        respect_retry_after_header=True,
    )
    adapter = HTTPAdapter(max_retries=retry)
    session = requests.Session()
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    return session


def iter_issue_pages(
    owner: str,
    repo: str,
    token: str | None,
    *,
    session: requests.Session,
    state: str = "all",
    per_page: int = 100,
) -> Iterator[list[dict]]:
    """Yield issue pages from *owner/repo* using pagination."""
    start = time.perf_counter()
    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues"
    params: dict = {"state": state, "per_page": per_page, "page": 1}
    pages = 0
    issues = 0

    with tqdm(desc="Fetching issues", unit="page") as bar:
        while True:
            page_start = time.perf_counter()
            resp = session.get(url, headers=_headers(token), params=params, timeout=30)
            _handle_rate_limit(resp)
            resp.raise_for_status()
            page = resp.json()
            if not page:
                break
            pages += 1
            issues += len(page)
            page_elapsed_ms = (time.perf_counter() - page_start) * 1000
            current_kib, peak_kib = _memory_kib()
            log.info(
                "perf.fetch_issue_page page=%d items=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
                params["page"],
                len(page),
                page_elapsed_ms,
                current_kib,
                peak_kib,
            )
            yield page
            bar.update(1)
            params["page"] += 1

    elapsed_ms = (time.perf_counter() - start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.iter_issue_pages pages=%d issues=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        pages,
        issues,
        elapsed_ms,
        current_kib,
        peak_kib,
    )
    log.info("Fetched %d issue(s) from %s/%s.", issues, owner, repo)


def _handle_rate_limit(resp: requests.Response) -> None:
    remaining = int(resp.headers.get("X-RateLimit-Remaining", 1))
    if remaining == 0:
        reset = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
        wait = max(0, reset - int(time.time())) + 1
        log.warning("Rate limit hit; sleeping %ds.", wait)
        time.sleep(wait)


def issues_to_rows(issues: list[dict]) -> list[dict[str, str]]:
    rows = []
    for issue in issues:
        rows.append({
            "number": str(issue.get("number", "")),
            "title": issue.get("title", ""),
            "state": issue.get("state", ""),
            "created_at": issue.get("created_at", ""),
            "updated_at": issue.get("updated_at", ""),
            "html_url": issue.get("html_url", ""),
            "user": (issue.get("user") or {}).get("login", ""),
        })
    return rows


def main(args: argparse.Namespace) -> int:
    log.info(
        "fetch_github_issues starting (repo=%s/%s, dry_run=%s)",
        args.owner,
        args.repo,
        args.dry_run,
    )

    token = args.token or os.environ.get("GITHUB_TOKEN")
    if not token:
        log.warning("No GitHub token provided; requests may be heavily rate-limited.")

    session = _build_session()
    output = Path(args.output)
    total_rows = 0
    write_start = time.perf_counter()

    try:
        if args.dry_run:
            for page in iter_issue_pages(args.owner, args.repo, token, state=args.state, session=session):
                total_rows += len(page)
            log.info("[dry-run] Would write %d row(s) to '%s'.", total_rows, output)
            return 0

        output.parent.mkdir(parents=True, exist_ok=True)
        with output.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=ISSUES_FIELDS)
            writer.writeheader()
            for page in iter_issue_pages(args.owner, args.repo, token, state=args.state, session=session):
                rows = issues_to_rows(page)
                writer.writerows(rows)
                total_rows += len(rows)
    finally:
        session.close()

    elapsed_ms = (time.perf_counter() - write_start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.write_issues_csv rows=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        total_rows,
        elapsed_ms,
        current_kib,
        peak_kib,
    )
    log.info("Wrote %d issue(s) to '%s'.", total_rows, output)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch GitHub Issues for a repository and export to CSV."
    )
    parser.add_argument("owner", help="Repository owner (user or org).")
    parser.add_argument("repo", help="Repository name.")
    parser.add_argument("--output", default="issues.csv", help="Output CSV path.")
    parser.add_argument("--state", default="all", choices=["open", "closed", "all"])
    parser.add_argument(
        "--token",
        default=None,
        help="GitHub personal access token (or set GITHUB_TOKEN env var).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
