"""
merge_csvs.py — Merge multiple CSV files, normalize headers, and produce a summary report.

This is a sample data-processing script generated by Copilot Script Agent.
It demonstrates: pandas-free CSV merging using stdlib csv, tqdm progress bars,
--dry-run support, and structured logging.
"""

from __future__ import annotations

import argparse
import csv
import sys
import time
from pathlib import Path

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger
from scripts.common.file_ops import safe_write

log = get_logger(__name__)


def _log_perf(stage: str, started_at: float, **fields: int | str | None) -> None:
    elapsed_ms = (time.perf_counter() - started_at) * 1000
    metrics = " ".join(f"{k}={v}" for k, v in fields.items())
    log.info("perf.%s elapsed_ms=%.2f %s", stage, elapsed_ms, metrics)


def normalize_header(header: list[str]) -> list[str]:
    """Return a normalized version of *header* (lowercase, underscores, stripped)."""
    return [col.strip().lower().replace(" ", "_").replace("-", "_") for col in header]


def discover_headers(input_paths: list[Path]) -> list[str]:
    """Read headers across files and return a normalized unified header list."""
    started_at = time.perf_counter()
    all_headers: list[str] = []

    for path in tqdm(input_paths, desc="Reading CSVs", unit="file"):
        with path.open(encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                log.warning("Skipping '%s': no headers found.", path)
                continue
            norm = normalize_header(list(reader.fieldnames))
            for h in norm:
                if h not in all_headers:
                    all_headers.append(h)

    _log_perf("read_normalize", started_at, files=len(input_paths), columns=len(all_headers))
    return all_headers


def stream_rows(
    input_paths: list[Path],
    headers: list[str],
    output_path: Path,
    *,
    dry_run: bool,
) -> int:
    """Stream normalized rows from inputs to output and return total row count."""
    started_at = time.perf_counter()
    total_rows = 0

    writer: csv.DictWriter | None = None
    out_fh = None
    if not dry_run:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        out_fh = output_path.open("w", encoding="utf-8", newline="")
        writer = csv.DictWriter(out_fh, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()

    try:
        for path in tqdm(input_paths, desc="Writing merged CSV", unit="file"):
            with path.open(encoding="utf-8", newline="") as fh:
                reader = csv.DictReader(fh)
                if reader.fieldnames is None:
                    continue
                norm = normalize_header(list(reader.fieldnames))
                mapping = dict(zip(reader.fieldnames, norm))
                for row in reader:
                    normalized_row = {mapping[k]: v for k, v in row.items()}
                    if writer is not None:
                        writer.writerow(normalized_row)
                    total_rows += 1
    finally:
        if out_fh is not None:
            out_fh.close()

    _log_perf("write", started_at, files=len(input_paths), rows=total_rows, dry_run=dry_run)
    return total_rows


def build_summary(headers: list[str], row_count: int) -> str:
    """Return a plain-text summary report."""
    lines = [
        f"Summary Report",
        f"==============",
        f"Total rows   : {row_count}",
        f"Columns ({len(headers)}): {', '.join(headers)}",
    ]
    return "\n".join(lines)


def main(args: argparse.Namespace) -> int:
    log.info("merge_csvs starting (dry_run=%s)", args.dry_run)

    input_paths = [Path(p) for p in args.inputs]
    missing = [p for p in input_paths if not p.exists()]
    if missing:
        log.error("Files not found: %s", missing)
        return 1

    headers = discover_headers(input_paths)
    output_path = Path(args.output)
    row_count = stream_rows(input_paths, headers, output_path, dry_run=args.dry_run)
    log.info("Merged %d row(s) across %d file(s).", row_count, len(input_paths))

    if args.dry_run:
        log.info("[dry-run] Would write merged CSV to '%s'.", output_path)
    else:
        log.info("Merged CSV written to '%s'.", output_path)

    # Write summary report
    summary = build_summary(headers, row_count)
    report_path = output_path.with_suffix(".txt")
    safe_write(report_path, summary, dry_run=args.dry_run)

    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge multiple CSV files and produce a summary.")
    parser.add_argument("inputs", nargs="+", help="Input CSV file paths.")
    parser.add_argument("--output", default="merged.csv", help="Output CSV path (default: merged.csv).")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
