"""
merge_csvs.py — Merge multiple CSV files, normalize headers, and produce a summary report.

This is a sample data-processing script generated by Copilot Script Agent.
It demonstrates: pandas-free CSV merging using stdlib csv, tqdm progress bars,
--dry-run support, and structured logging.
"""

from __future__ import annotations

import argparse
import csv
import sys
import time
import tracemalloc
from pathlib import Path
from typing import Iterator

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger
from scripts.common.file_ops import safe_write

log = get_logger(__name__)

if not tracemalloc.is_tracing():
    tracemalloc.start()


def normalize_header(header: list[str]) -> list[str]:
    """Return a normalized version of *header* (lowercase, underscores, stripped)."""
    return [col.strip().lower().replace(" ", "_").replace("-", "_") for col in header]


def _memory_kib() -> tuple[float, float]:
    current, peak = tracemalloc.get_traced_memory()
    return current / 1024.0, peak / 1024.0


def discover_headers(input_paths: list[Path]) -> list[str]:
    """Return unified normalized headers for *input_paths*."""
    start = time.perf_counter()
    all_headers: list[str] = []

    for path in tqdm(input_paths, desc="Reading CSVs", unit="file"):
        with path.open(encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                log.warning("Skipping '%s': no headers found.", path)
                continue
            norm = normalize_header(list(reader.fieldnames))
            for h in norm:
                if h not in all_headers:
                    all_headers.append(h)

    elapsed_ms = (time.perf_counter() - start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.discover_headers files=%d headers=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        len(input_paths),
        len(all_headers),
        elapsed_ms,
        current_kib,
        peak_kib,
    )
    return all_headers


def iter_merged_rows(input_paths: list[Path]) -> Iterator[dict[str, str]]:
    """Yield normalized rows from *input_paths* incrementally."""
    for path in input_paths:
        with path.open(encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                continue
            norm = normalize_header(list(reader.fieldnames))
            mapping = dict(zip(reader.fieldnames, norm))
            for row in reader:
                yield {mapping[k]: v for k, v in row.items()}


def build_summary(headers: list[str], row_count: int) -> str:
    """Return a plain-text summary report."""
    lines = [
        f"Summary Report",
        f"==============",
        f"Total rows   : {row_count}",
        f"Columns ({len(headers)}): {', '.join(headers)}",
    ]
    return "\n".join(lines)


def main(args: argparse.Namespace) -> int:
    log.info("merge_csvs starting (dry_run=%s)", args.dry_run)

    input_paths = [Path(p) for p in args.inputs]
    missing = [p for p in input_paths if not p.exists()]
    if missing:
        log.error("Files not found: %s", missing)
        return 1

    headers = discover_headers(input_paths)
    row_count = 0

    # Write merged CSV
    output_path = Path(args.output)
    if args.dry_run:
        dry_start = time.perf_counter()
        for _ in tqdm(iter_merged_rows(input_paths), desc="Reading merged rows", unit="row"):
            row_count += 1
        elapsed_ms = (time.perf_counter() - dry_start) * 1000
        current_kib, peak_kib = _memory_kib()
        log.info(
            "perf.read_merged_rows rows=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
            row_count,
            elapsed_ms,
            current_kib,
            peak_kib,
        )
        log.info("[dry-run] Would write merged CSV (%d row(s)) to '%s'.", row_count, output_path)
    else:
        write_start = time.perf_counter()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=headers, extrasaction="ignore")
            writer.writeheader()
            with tqdm(desc="Writing merged CSV", unit="row") as bar:
                for row in iter_merged_rows(input_paths):
                    writer.writerow(row)
                    row_count += 1
                    bar.update(1)
        log.info("Merged CSV written to '%s'.", output_path)
        elapsed_ms = (time.perf_counter() - write_start) * 1000
        current_kib, peak_kib = _memory_kib()
        log.info(
            "perf.write_merged_csv rows=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
            row_count,
            elapsed_ms,
            current_kib,
            peak_kib,
        )
    log.info("Merged %d row(s) across %d file(s).", row_count, len(input_paths))

    # Write summary report
    summary = build_summary(headers, row_count)
    report_path = output_path.with_suffix(".txt")
    safe_write(report_path, summary, dry_run=args.dry_run)

    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge multiple CSV files and produce a summary.")
    parser.add_argument("inputs", nargs="+", help="Input CSV file paths.")
    parser.add_argument("--output", default="merged.csv", help="Output CSV path (default: merged.csv).")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
