"""
md_to_text.py — Convert Markdown files to plain text with a progress bar.

This is a sample utilities script generated by Copilot Script Agent.
It demonstrates: batch file conversion, tqdm progress bars,
--dry-run support, and structured logging.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import re
import sys
import time
import tracemalloc
from pathlib import Path
from typing import Iterable, Iterator

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger
from scripts.common.file_ops import safe_write

log = get_logger(__name__)

if not tracemalloc.is_tracing():
    tracemalloc.start()


def _memory_kib() -> tuple[float, float]:
    current, peak = tracemalloc.get_traced_memory()
    return current / 1024.0, peak / 1024.0


def md_to_text(md: str) -> str:
    """Strip common Markdown syntax and return plain text."""
    # Remove fenced code blocks
    text = re.sub(r"```[^\n]*\n.*?```", "", md, flags=re.DOTALL)
    # Remove inline code
    text = re.sub(r"`[^`]+`", lambda m: m.group(0)[1:-1], text)
    # Remove headings
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Remove bold/italic
    text = re.sub(r"\*{1,2}([^*]+)\*{1,2}", r"\1", text)
    text = re.sub(r"_{1,2}([^_]+)_{1,2}", r"\1", text)
    # Remove links, keep text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # Remove images
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    # Remove horizontal rules
    text = re.sub(r"^[-*_]{3,}\s*$", "", text, flags=re.MULTILINE)
    # Collapse blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def convert_files(
    input_paths: Iterable[Path],
    output_dir: Path,
    *,
    dry_run: bool,
) -> int:
    """Convert *input_paths* to plain text in *output_dir*."""
    start = time.perf_counter()
    converted = 0
    for src in tqdm(input_paths, desc="Converting", unit="file"):
        dest = output_dir / src.with_suffix(".txt").name
        md = src.read_text(encoding="utf-8")
        plain = md_to_text(md)
        safe_write(dest, plain, dry_run=dry_run)
        converted += 1
    elapsed_ms = (time.perf_counter() - start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.convert_files converted=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        converted,
        elapsed_ms,
        current_kib,
        peak_kib,
    )
    return converted


def iter_markdown_files(
    input_dir: Path,
    *,
    include_pattern: str = "*.md",
    exclude_pattern: str | None = None,
    max_depth: int | None = None,
    limit: int | None = None,
) -> Iterator[Path]:
    """Yield Markdown files incrementally with optional scan controls."""
    start = time.perf_counter()
    yielded = 0
    for root, dirs, names in os.walk(input_dir, topdown=True):
        root_path = Path(root)
        rel_root = root_path.relative_to(input_dir)
        depth = 0 if str(rel_root) == "." else len(rel_root.parts)
        if max_depth is not None and (depth + 1) > max_depth:
            dirs[:] = []
        for name in names:
            if not fnmatch.fnmatch(name, include_pattern):
                continue
            if max_depth is not None and depth > max_depth:
                continue
            path = root_path / name
            rel_str = str(path.relative_to(input_dir))
            if exclude_pattern and fnmatch.fnmatch(rel_str, exclude_pattern):
                continue
            yield path
            yielded += 1
            if limit is not None and yielded >= limit:
                break
        if limit is not None and yielded >= limit:
            break
    elapsed_ms = (time.perf_counter() - start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.iter_markdown_files root=%s yielded=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        input_dir,
        yielded,
        elapsed_ms,
        current_kib,
        peak_kib,
    )


def main(args: argparse.Namespace) -> int:
    log.info("md_to_text starting (dry_run=%s)", args.dry_run)
    scan_root = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    count = convert_files(
        iter_markdown_files(
            scan_root,
            include_pattern=args.include,
            exclude_pattern=args.exclude,
            max_depth=args.max_depth,
            limit=args.limit,
        ),
        output_dir,
        dry_run=args.dry_run,
    )
    if count == 0:
        log.warning("No Markdown files found in '%s'.", args.input_dir)
        return 0

    log.info("Found %d Markdown file(s).", count)
    log.info("Converted %d file(s).", count)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert Markdown files to plain text."
    )
    parser.add_argument("--input-dir", default=".", help="Directory to scan for .md files.")
    parser.add_argument("--output-dir", default="./output", help="Destination directory for .txt files.")
    parser.add_argument(
        "--include",
        default="*.md",
        help="File name pattern to include during scan (default: *.md).",
    )
    parser.add_argument(
        "--exclude",
        default=None,
        help="Optional relative path glob pattern to exclude.",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=None,
        help="Maximum scan depth relative to input-dir.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Maximum number of files to process.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without writing files.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
