"""
archive_old_logs.py — Archive log files older than N days to a backup folder.

This is a sample system-automation script generated by Copilot Script Agent.
It demonstrates the standard script template: main(), argparse with --dry-run,
structured logging, and tqdm progress bars.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import shutil
import sys
import time
import tracemalloc
from datetime import datetime, timedelta
from pathlib import Path
from typing import Iterable, Iterator

# Ensure the repository root is on sys.path when this script is run directly.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tqdm import tqdm

from scripts.common.logger import get_logger

log = get_logger(__name__)

if not tracemalloc.is_tracing():
    tracemalloc.start()


def _memory_kib() -> tuple[float, float]:
    current, peak = tracemalloc.get_traced_memory()
    return current / 1024.0, peak / 1024.0


def iter_old_logs(
    log_dir: Path,
    days: int,
    *,
    include_pattern: str = "*.log",
    exclude_pattern: str | None = None,
    max_depth: int | None = None,
    limit: int | None = None,
) -> Iterator[Path]:
    """Yield log files in *log_dir* older than *days* days."""
    start = time.perf_counter()
    cutoff = datetime.now() - timedelta(days=days)
    matched = 0
    scanned = 0
    for root, dirs, names in os.walk(log_dir, topdown=True):
        root_path = Path(root)
        rel_root = root_path.relative_to(log_dir)
        depth = 0 if str(rel_root) == "." else len(rel_root.parts)
        for name in names:
            if not fnmatch.fnmatch(name, include_pattern):
                continue
            p = root_path / name
            scanned += 1
            rel_str = str(p.relative_to(log_dir))
            if exclude_pattern and fnmatch.fnmatch(rel_str, exclude_pattern):
                continue
            if datetime.fromtimestamp(p.stat().st_mtime) < cutoff:
                matched += 1
                yield p
                if limit is not None and matched >= limit:
                    break
        if max_depth is not None and depth >= max_depth:
            dirs[:] = []
        if limit is not None and matched >= limit:
            break
    elapsed_ms = (time.perf_counter() - start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.iter_old_logs root=%s scanned=%d matched=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        log_dir,
        scanned,
        matched,
        elapsed_ms,
        current_kib,
        peak_kib,
    )


def archive_logs(
    files: Iterable[Path],
    backup_dir: Path,
    *,
    dry_run: bool,
) -> int:
    """Copy *files* to *backup_dir*.  Returns the number of files archived."""
    start = time.perf_counter()
    archived = 0
    for src in tqdm(files, desc="Archiving logs", unit="file"):
        dest = backup_dir / src.name
        if dry_run:
            log.info("[dry-run] Would archive '%s' → '%s'.", src, dest)
        else:
            backup_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            log.info("Archived '%s' → '%s'.", src, dest)
        archived += 1
    elapsed_ms = (time.perf_counter() - start) * 1000
    current_kib, peak_kib = _memory_kib()
    log.info(
        "perf.archive_logs archived=%d elapsed_ms=%.2f mem_current_kib=%.2f mem_peak_kib=%.2f",
        archived,
        elapsed_ms,
        current_kib,
        peak_kib,
    )
    return archived


def main(args: argparse.Namespace) -> int:
    log.info(
        "archive_old_logs starting (log_dir=%s, days=%d, dry_run=%s)",
        args.log_dir,
        args.days,
        args.dry_run,
    )

    log_dir = Path(args.log_dir)
    if not log_dir.exists():
        log.error("Log directory '%s' does not exist.", log_dir)
        return 1

    backup_dir = Path(args.backup_dir)
    count = archive_logs(
        iter_old_logs(
            log_dir,
            args.days,
            include_pattern=args.include,
            exclude_pattern=args.exclude,
            max_depth=args.max_depth,
            limit=args.limit,
        ),
        backup_dir,
        dry_run=args.dry_run,
    )
    log.info("Found %d log file(s) older than %d day(s).", count, args.days)
    if count == 0:
        log.info("Nothing to archive.")
        return 0
    log.info("Archived %d file(s).", count)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Archive log files older than N days to a backup folder."
    )
    parser.add_argument("--log-dir", default="/var/log", help="Directory to scan.")
    parser.add_argument("--backup-dir", default="/var/log/archive", help="Backup destination.")
    parser.add_argument("--days", type=int, default=30, help="Age threshold in days (default: 30).")
    parser.add_argument(
        "--include",
        default="*.log",
        help="File name pattern to include during scan (default: *.log).",
    )
    parser.add_argument(
        "--exclude",
        default=None,
        help="Optional relative path glob pattern to exclude.",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=None,
        help="Maximum scan depth relative to log-dir.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Maximum number of files to archive.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be done without making changes.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main(parse_args()))
